### Clase 3 de Sept

# Bayes

In [10]:
# Librerias y datos
import pandas as pd

# Cargar dataset
df = pd.read_csv(
    "meteorologia/meteorología_2025.csv",
    skiprows=9,
    low_memory=False
)

df.head()

                  date id_station id_parameter  valor  unit
0  2025-01-01 00:00:00        ACO          TMP    8.7     5
1  2025-01-01 00:00:00        ACO           RH   28.0     6
2  2025-01-01 00:00:00        ACO          WSP    2.4     3
3  2025-01-01 00:00:00        ACO          WDR    2.0     4
4  2025-01-01 00:00:00        AJM          TMP    9.6     5

In [11]:
# Selección de estación y parametros

# Estación
uax = df[df["id_station"] == "UAX"]

# Parámetros
uax = uax[uax["id_parameter"].isin(["RH", "WSP"])]

# Convertimos de formato largo a formato ancho
uax = uax.pivot(
    index="date",
    columns="id_parameter",
    values="valor"
).reset_index()

# Quitamos las filas donde falten los parámetros
uax = uax.dropna(subset=["RH", "WSP"])

uax.head()

id_parameter                 date    RH  WSP
0             2025-01-01 00:00:00  41.0  1.1
1             2025-01-01 01:00:00  45.0  1.1
2             2025-01-01 02:00:00  46.0  1.0
3             2025-01-01 03:00:00  55.0  0.2
4             2025-01-01 04:00:00  55.0  1.1

In [12]:
# Definimos eventos 
humedad_alta = uax["RH"] >= 70
viento_tranquilo = uax["WSP"] <= 1

# Intersección de ambos eventos
ambos = humedad_alta & viento_tranquilo

## Probabilidades

In [13]:
# Probabilidades simples
p_humedad_alta = humedad_alta.mean()
p_viento_tranquilo = viento_tranquilo.mean()

In [14]:
# Probabilidades condicionales
p_hum_dado_viento = ambos.sum() / viento_tranquilo.sum()
p_viento_dado_hum = ambos.sum() / humedad_alta.sum()

In [15]:
# Resultados
print(
    "P(Humedad alta):",
    round(p_humedad_alta, 4),
    "=",
    round(p_humedad_alta * 100, 2),
    "%"
)

print(
    "P(Viento tranquilo):",
    round(p_viento_tranquilo, 4),
    "=",
    round(p_viento_tranquilo * 100, 2),
    "%"
)

print(
    "P(Hum alta | Viento tranquilo):",
    round(p_hum_dado_viento, 4),
    "=",
    round(p_hum_dado_viento * 100, 2),
    "%"
)

print(
    "P(Viento tranquilo | Hum alta):",
    round(p_viento_dado_hum, 4),
    "=",
    round(p_viento_dado_hum * 100, 2),
    "%"
)

P(Humedad alta): 0.3583 = 35.83 %
P(Viento tranquilo): 0.2213 = 22.13 %
P(Hum alta | Viento tranquilo): 0.6739 = 67.39 %
P(Viento tranquilo | Hum alta): 0.4162 = 41.62 %